In [1]:
import numpy as np

In [4]:
#  Arrays are important because they enable you to express batch operations on data
#  without writing any for loops. NumPy users call this vectorization


In [5]:
 arr = np.array([[1., 2., 3.], [4., 5., 6.]])


In [8]:
print(arr)
print(arr.ndim)

[[1. 2. 3.]
 [4. 5. 6.]]
2


In [9]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# Arithmetic operations with scalars propagate the scalar argument to each element in
# the array:

In [12]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [13]:
 arr ** 0.5


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [24]:
ar =np.array([1,2,3,4])
ar * 0.5

array([0.5, 1. , 1.5, 2. ])

In [25]:
ar =np.array([1,2,3,4])
ar ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
# Comparisons between arrays of the same size yield boolean arrays:


In [28]:
 arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


In [29]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [30]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [31]:
# Operations between differently sized arrays is called broadcasting

# Basic Indexing and Slicing


In [32]:
arr=np.arange(10)

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr[3]

3

In [35]:
arr[-2]

8

In [36]:
 arr[5:8]


array([5, 6, 7])

In [41]:
arr[-5:-2]

array([5, 6, 7])

In [42]:
 arr[5:8] = 12

In [43]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [45]:
arr[-5:-2]

array([12, 12, 12])

In [46]:
arr[-5:-2]=10

In [47]:
arr

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

In [ ]:
# . An important first dis‐
#   tinction from Python’s built-in lists is that array slices are views on the original array.
#   This means that the data is not copied, and any modifications to the view will be
#    reflected in the source array.
#

In [49]:
 arr_slice = arr[5:8]


In [50]:
arr_slice

array([10, 10, 10])

In [51]:
# Now, when I change values in arr_slice, the mutations are reflected in the original
# array arr:

In [52]:
arr_slice[1] = 12345

In [53]:
arr_slice

array([   10, 12345,    10])

In [54]:
arr

array([    0,     1,     2,     3,     4,    10, 12345,    10,     8,
           9])

In [55]:
# The “bare” slice [:] will assign to all values in an array

In [56]:
arr_slice[:]= 64

In [57]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [58]:
# . In a two-dimensionalarray, the elements at each index are no longer scalars but rather one-dimensional
# arrays:

In [59]:
 arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [60]:
arr2d[2]

array([7, 8, 9])

In [61]:
# Thus, individual elements can be accessed recursively. But that is a bit too much
# work, so you can pass a comma-separated list of indices to select individual elements.
# So these are equivalent:

In [62]:
 arr2d[0][2]


3

In [63]:
arr2d[0,2]

3

In [64]:
#   an illustration of indexing on a two-dimensional array. I find it
#   helpful to think of axis 0 as the “rows” of the array and axis 1 as the “columns.”
#

In [67]:
 arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [66]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
old_values = arr3d[0].copy()


In [69]:
arr3d[0]= 42

In [70]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
 arr3d[0] = old_values


In [72]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
 arr3d[1, 0]


array([7, 8, 9])

In [76]:
 x = arr3d[1]


In [77]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [78]:
 x[0]


array([7, 8, 9])

# Indexing with slices


In [79]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [80]:
 arr[1:6]


array([ 1,  2,  3,  4, 64])

In [81]:
# Consider the two-dimensional array from before, arr2d. Slicing this array is a bit
# different:

In [82]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
 arr2d[:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
# As you can see, it has sliced along axis 0, the first axis. A slice, therefore, selects a
# range of elements along an axis. It can be helpful to read the expression arr2d[:2] as
# “select the first two rows of arr2d.”

In [85]:
 arr2d[:2, 1:]


array([[2, 3],
       [5, 6]])

In [2]:
import numpy as np

In [4]:
 arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [5]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
 arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2d[0:1]

array([[1, 2, 3]])

In [8]:
arr2d[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2d[2:]

array([[7, 8, 9]])

In [13]:
arr2d[1:2]

array([[4, 5, 6]])

In [14]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
 arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [16]:
 arr2d[1, :2]


array([4, 5])

In [17]:
arr2d[2, 1:2]

array([8])

In [18]:
 arr2d[:2, 2]


array([3, 6])

In [19]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2d[2,2]

9

In [24]:
 arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [25]:
 arr2d[:2, 1:] = 0


In [26]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])