In [1]:
import numpy as np

In [11]:
a = [1,2,3,43]
type(a)

list

In [12]:
arr =  np.array([1,2,3,4,5])    # this is a array

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)   #  we can check type of array

numpy.ndarray

In [7]:
arr1 = np.array((1,2,3,4,5))   #  This is a Tuple

In [13]:
print(arr1)

[1 2 3 4 5]


In [9]:
type(arr1)

numpy.ndarray

In [14]:
arr2 = [ 1,2,3,4,5]   #  this is a list

In [15]:
type(arr2)

list

In [16]:
arr = np.array(arr2)   #  in numpy array we can pass dictionary,list,tuple and convert into array.

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr

array([1, 2, 3, 4, 5])

# 0-D Arrays


In [ ]:
#  0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [19]:
arr = np.array(100)

In [20]:
print(arr)

100


In [21]:
type(arr)

numpy.ndarray

In [22]:
arr.ndim

0

# 1-D Arrays


In [23]:
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.



In [24]:
arr = np.array([1, 2, 3, 4, 5])


In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr.ndim

1

# 2-D Arrays


In [27]:
# An array that has 1-D arrays as its elements is called a 2-D array.

# These are often used to represent matrix or 2nd order tensors.

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [29]:
arr.ndim

2

# 3-D arrays


In [30]:
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

#These are often used to represent a 3rd order tensor.

In [31]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


In [32]:
arr.ndim

3

In [33]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

# Higher Dimensional Arrays


In [34]:
# An array can have any number of dimensions.

# When the array is created, you can define the number of dimensions by using the ndmin argument.

In [35]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [36]:
arr.ndim

5

In [37]:
print('number of dimensions :', arr.ndim)


number of dimensions : 5


#  NumPy Array Indexing


In [38]:
# Array indexing is the same as accessing an array element.

# You can access an array element by referring to its index number.

# The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [39]:
import numpy as np


In [41]:
arr = np.array([1, 2, 3, 4])

arr[2]    # we give index and get the number/value

3

In [42]:
# Get third and fourth elements from the following array .

print(arr[0],arr[3])

1 4


In [43]:
# Get third and fourth elements from the following array and add them.

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])     #  3+4



7


# Access 2-D Arrays


In [44]:
# To access elements from 2-D arrays we can use comma separated integers representing the dimension 
# and the index of the element.



In [45]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


In [46]:
# We got 3 in 1st dim

arr[0,2]

3

In [47]:
# we got 9 in dim 2nd

In [48]:
arr[1,3]

9

# Access 3-D Arrays


In [49]:
# To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.



In [53]:
# Access the third element of the second array of the first array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr[0,1,2]

6

# Negative Indexing


In [54]:
# Use negative indexing to access an array from the end.



In [55]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


In [58]:
print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


# NumPy Array Slicing


In [59]:
import numpy as np

Slicing arrays


In [60]:
# We pass slice instead of index like this: [start:end].

# We can also define the step, like this: [start:end:step].

# If we don't pass start its considered 0

# If we don't pass end its considered length of array in that dimension

# If we don't pass step its considered 1

In [61]:
# Slice elements from index 1 to index 5 from the following array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[1:5]

array([2, 3, 4, 5])

In [62]:
# Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[4:]

array([5, 6, 7])

In [63]:
# Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[:4]

array([1, 2, 3, 4])

In [64]:
# Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[-3:-1]


array([5, 6])

# STEP


In [65]:
# Use the step value to determine the step of the slicing:



In [66]:
# Return every other element from index 1 to index 5:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

arr[1:5:2]

array([2, 4])

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


[1 3 5 7]


# Slicing 2-D Arrays


In [68]:
# From the second element, slice elements from index 1 to index 4 (not included):



In [69]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])


[7 8 9]


In [70]:
arr[0,1:3]

array([2, 3])

In [72]:
print(arr[0:2, 2])  


[3 8]


In [73]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])


[[2 3 4]
 [7 8 9]]


In [79]:
arr[0:2,1:4]   # 1st element indicate of index and , 2nd is doing slicing

array([[2, 3, 4],
       [7, 8, 9]])