In [ ]:
import numpy as np

In [ ]:
# Transposing is a special form of reshaping that similarly returns a view on the under‐
# lying data without copying anything. Arrays have the transpose method and also the
# special T attribute:

In [ ]:
arr = np.arange(15).reshape((3, 5))


In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T      #  Capital "T" attribute used for transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
#  for example, when computing the inner matrix product using np.dot:


In [ ]:
 arr = np.random.randn(6, 3)


In [ ]:
arr

array([[ 0.49250542,  1.70999708,  2.02871733],
       [ 0.35344166, -0.35811451, -0.67732691],
       [-0.10359504,  1.27202698,  0.81382815],
       [-0.29398881,  0.00972953,  0.84408748],
       [ 0.08032281, -0.05163134,  2.36277982],
       [ 0.12826563,  0.32473496,  0.1170592 ]])

In [14]:
array = np.arange(18).reshape((6,3))

In [15]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [16]:
 np.dot(array.T, array)


array([[495, 540, 585],
       [540, 591, 642],
       [585, 642, 699]])

In [17]:
array.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [19]:
array * array

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196],
       [225, 256, 289]])

In [20]:
 np.dot(arr.T, arr)


array([[ 0.48754778,  0.61847934,  0.63209769],
       [ 0.61847934,  4.77860192,  4.67110496],
       [ 0.63209769,  4.67110496, 11.54569698]])

In [21]:
 arr = np.arange(16).reshape((2, 2, 4))


In [22]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [23]:
arr2 = np.array([[[0,1,2,3,],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])

In [24]:
arr2       

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [30]:
arr == arr2     #  both array have same values and shape

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [31]:
 arr = np.arange(16).reshape((2, 2, 4))


In [32]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [33]:
 arr.transpose((1, 0, 2))


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr2 = np.array([[[0,1,2,3,],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])

In [38]:
 arr.transpose((1, 0,2))


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [39]:
#Simple transposing with .T is a special case of swapping axes. ndarray has the method
#swapaxes, which takes a pair of axis numbers and switches the indicated axes to rear‐
#range the data:

In [40]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [49]:
 ar = arr.T
 ar
 
 
#  arr.swapaxes(1, 2) 


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [50]:
  arr.swapaxes(1, 2) 

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

#4.2 Universal Functions: Fast Element-Wise Array Function


In [51]:
"""A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results.
Many ufuncs are simple element-wise transformations, like sqrt or exp:"""

In [52]:
 arr = np.arange(10)


In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
 np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [57]:
 np.exp(arr)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [60]:
arr3 = np.arange(4,9)
arr3

array([4, 5, 6, 7, 8])

In [61]:
np.sqrt(arr3)

array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [62]:
np.exp(arr3)

array([  54.59815003,  148.4131591 ,  403.42879349, 1096.63315843,
       2980.95798704])

In [63]:
"""These are referred to as unary ufuncs. Others, such as add or maximum, take two arrays
(thus, binary ufuncs) and return a single array as the result:
"""

In [64]:
x = np.random.randn(8)


In [66]:
 y = np.random.randn(8)

In [67]:
x

array([-0.54496182, -0.59562724, -0.15846071,  0.00857953,  0.17445751,
        0.2351704 ,  0.48170126,  0.48454367])

In [68]:
y

array([-0.09511957, -0.74107061, -1.36153952,  1.5459787 , -0.03249114,
        0.2672663 ,  1.60153712, -0.41506618])

In [74]:
 np.maximum(x, y)


array([-0.09511957, -0.59562724, -0.15846071,  1.5459787 ,  0.17445751,
        0.2672663 ,  1.60153712,  0.48454367])

In [75]:
np.minimum(x,y)

array([-0.54496182, -0.74107061, -1.36153952,  0.00857953, -0.03249114,
        0.2351704 ,  0.48170126, -0.41506618])

In [75]:
""", a ufunc can return multiple arrays. modf is one example, a vec‐
torized version of the built-in Python divmod; it returns the fractional and integral
parts of a floating-point array:"""

In [76]:
 arr = np.random.randn(7) * 5


In [77]:
arr

array([-1.61048845, -4.19574161, -2.35731733, -3.0942994 , -2.28665815,
       -2.16434392, -1.27684108])

In [102]:
  a2 = np.arange(1,7) 
  print(a2)
  n2 = a1 * 5
  print( n2)
  #n1 =np.array( a1 * 5)
  #print(n1)

[1 2 3 4 5 6]
[ 5 10 15 20 25 30]


In [103]:
 remainder, whole_part = np.modf(arr)


In [104]:
remainder

array([-0.61048845, -0.19574161, -0.35731733, -0.0942994 , -0.28665815,
       -0.16434392, -0.27684108])

In [105]:
whole_part

array([-1., -4., -2., -3., -2., -2., -1.])

In [111]:
#Ufuncs accept an optional out argument that allows them to operate in-place on
#arrays:

In [112]:
arr

array([-1.61048845, -4.19574161, -2.35731733, -3.0942994 , -2.28665815,
       -2.16434392, -1.27684108])

In [113]:
 np.sqrt(arr)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan, nan, nan, nan, nan, nan, nan])

In [115]:
 arr = np.random.randn(7) * 5


In [116]:
 np.sqrt(arr)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 1.2184416 , 2.30065034, 2.49860641,        nan,
       1.54213769, 1.53410225])

In [119]:
 np.sqrt(arr, arr)


array([       nan, 1.05063334, 1.23158008, 1.25725816,        nan,
       1.11437353, 1.11291905])

In [120]:
arr

array([       nan, 1.05063334, 1.23158008, 1.25725816,        nan,
       1.11437353, 1.11291905])